In [1]:
#numpy

In [2]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
#create array

In [140]:
sample_array = np.array([1,2,3,4])

In [6]:
sample_array

array([1, 2, 3, 4])

In [7]:
sample_array = np.array([3,4,6,8])

In [16]:
sample_array

array([1, 2, 3, 4])

In [17]:
#2D array (a matrix )with 2 row and 2 colums

In [19]:
sample_array_2 = np.array([[1,2,],[3,4]])

In [20]:
sample_array2

array([3, 4, 6, 8])

In [21]:
 #3Dtensor (2 matrices ,matrix each with 2 rows and 2 colums)

In [23]:
sample_tensor_3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [25]:
sample_tensor_3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [26]:
#Dimension

In [27]:
# 0--D Array(Scaler)5
# 1-D Array(Vector) [1,2,3,4]
# 2D D Array (Matrix) (row,colums)
# #3D Array (tensor) (row, colums, pages)

In [28]:
# Array properties

In [30]:
sample_array = np.array([[1,2,3],[4,5,6]])

In [31]:
sample_array

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
# shape

In [33]:
sample_array.shape

(2, 3)

In [34]:
#dimentions

In [35]:
sample_array.ndim

2

In [36]:
#total element

In [37]:
sample_array.size

6

In [43]:
sample_array.dtype

dtype('int64')

In [44]:
# 3D array 

In [48]:
sample_tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

sample_tensor

In [49]:
sample_tensor

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [46]:
# special array 

In [47]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [50]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [52]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [55]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [56]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [58]:
sample_array = np.array([10,20,30,40])

In [59]:
sample_array

array([10, 20, 30, 40])

In [60]:
sample_array[0]

np.int64(10)

In [61]:
sample_array[2]

np.int64(30)

In [62]:
sample_array[-1]

np.int64(40)

In [63]:
#slicing

In [64]:
sample_array[1:3]

array([20, 30])

In [65]:
# Array operation

In [66]:
a =np.array([1,2,3])

In [67]:
b = np.array([4,5,6])

In [68]:
a

array([1, 2, 3])

In [69]:
b

array([4, 5, 6])

In [70]:
a+b

array([5, 7, 9])

In [71]:
a-b

array([-3, -3, -3])

In [72]:
a*b

array([ 4, 10, 18])

In [73]:
a/b

array([0.25, 0.4 , 0.5 ])

In [74]:
#mathmatical function

In [75]:
sample_array = np.array([1,4,9])

In [77]:
sample_array

array([1, 4, 9])

In [78]:
np.sqrt(sample_array)

array([1., 2., 3.])

In [79]:
sample_array = np.array([10,40,90])

In [80]:
sample_array

array([10, 40, 90])

In [81]:
np.sqrt(sample_array)

array([3.16227766, 6.32455532, 9.48683298])

In [82]:
np.exp(sample_array)

array([2.20264658e+04, 2.35385267e+17, 1.22040329e+39])

In [83]:
np.log(sample_array)

array([2.30258509, 3.68887945, 4.49980967])

In [84]:
#statistcal function

In [86]:
sample_array = np.array([1,2,3,4,5])

In [87]:
sample_array

array([1, 2, 3, 4, 5])

In [88]:
np.mean(sample_array)

np.float64(3.0)

In [89]:
np.median(sample_array)

np.float64(3.0)

In [90]:
np.std(sample_array)

np.float64(1.4142135623730951)

In [91]:
np.min(sample_array)

np.int64(1)

In [92]:
np.max(sample_array)

np.int64(5)

In [95]:
#Reshaping Array

In [97]:
sample_array =  np.arange(6)

In [98]:
sample_array

array([0, 1, 2, 3, 4, 5])

In [100]:
reshaped = sample_array.reshape(2,3)

In [101]:
reshaped

array([[0, 1, 2],
       [3, 4, 5]])

In [103]:
#FALTERING

In [104]:
sample_array = np.array([[1,2],[3,4]])

In [105]:
sample_array

array([[1, 2],
       [3, 4]])

In [106]:
sample_array.flatten()

array([1, 2, 3, 4])

In [111]:
sample_tensor = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

In [112]:
sample_tensor

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [113]:
sample_tensor.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [114]:

#joining array

In [115]:
a = np.array([1,2])

In [116]:
b = np.array([3,4])

In [117]:
a

array([1, 2])

In [118]:
b

array([3, 4])

In [120]:
np.concatenate((a,b))

array([1, 2, 3, 4])

In [121]:
#spliting array

In [122]:
sample_array = np.array([1,2,3,4])

In [123]:
sample_array

array([1, 2, 3, 4])

In [124]:
np.array_split(sample_array,2)

[array([1, 2]), array([3, 4])]

In [125]:
#random module

In [126]:
np.random.rand(3)

array([0.25676573, 0.87513227, 0.54375165])

In [127]:
np.random.randint(1,10,5)

array([5, 7, 7, 4, 1], dtype=int32)

In [128]:
#  Axis concept

In [129]:
sample_array = np.array([[1,2],[3,4]])

In [130]:
sample_array

array([[1, 2],
       [3, 4]])

In [131]:
np.sum(sample_array,axis=0)

array([4, 6])

In [132]:
np.sum(sample_array,axis=1)

array([3, 7])

In [133]:
#NAN & Missing values

In [134]:
sample_array = np.array([1,np.nan,3])

In [135]:
sample_array

array([ 1., nan,  3.])

In [139]:
np.isnan(sample_array)

array([False,  True, False])

In [141]:
# create two numpy arrays and perform element wise addition substraction muultiplication and modulus operations

In [142]:
sample_array = np.array([1,2,3,4])

In [144]:
sample_array

array([1, 2, 3, 4])